services:
  redis:
    image: redis:7.4
    container_name: vinom_redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "--raw", "PING"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - redis_network

  app:
    build:
      context: . 
      dockerfile: Dockerfile
      target: prod-stage
    container_name: vinom_matchmaker
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
    volumes:
      - .:/app
      - /app/tmp 
    environment:
      HOST_IP: app
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      MAX_PLAYER: ${MAX_PLAYER}
      RANK_TOLERANCE: ${RANK_TOLERANCE}
      LATENCY_TOLERANCE: ${LATENCY_TOLERANCE}
    networks:
      - redis_network
    depends_on:
      redis:
        condition: service_healthy

networks:
  redis_network:
    driver: bridge

volumes:
  redis_data: 
